### ISSUE TITLE
This tool does not work as desired and clear steps to be provided

### ISSUE THREAD

**Issue by aws25** [gofore/aws-clean#6]
Traceback (most recent call last):
  File "./clean.py", line 156, in <module>
    boto_session = get_boto_session(config["profile_name"])
  File "./clean.py", line 149, in get_boto_session
    return boto3.Session(profile_name=profile_name)
  File "/usr/lib/python2.7/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/usr/lib/python2.7/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 726, in get_component
    return self._components.get_component(name)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 922, in get_component
    self._components[name] = factory()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 184, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 279, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 306, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 383, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (your-profile-name) could not be found

**Comment by rasathus** [comment]
It looks like you haven't updated the config example to use your credentials profile, as indicated in the comment ...

```
# Credentials profile name from your ~/.aws/credentials file
profile_name: your-profile-name
```

Hence the exception ...

```
botocore.exceptions.ProfileNotFound: The config profile (your-profile-name) could not be found
```

If you haven't configured additional profiles you could update this to 'default' to use the default profile.
